CREATE TABLE USER(
  ID INT NOT NULL AUTO_INCREMENT,
  FIRSTNAME VARCHAR(40) NOT NULL,
  LASTNAME VARCHAR(40),  
  EMAIL VARCHAR(100) NOT NULL,
  MOBILE_NO VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
);


